
# This is the network config written by 'subiquity'
network:
  ethernets:
    ens33:
      addresses:
      - 192.168.70.10/24
      - 192.168.70.110/24
      nameservers:
        addresses: []
        search: []
      routes:
      - to: 192.168.70.0/24
        via: 192.168.70.1

    ens34:
      dhcp4: true
      routes:
      - to: default
        via: 192.168.135.2

  version: 2





